//! The argument-list reference: the exact `bwrap` and `docker run` lists the library builds for
//! two fixed example layouts, computed by calling it, so the page cannot drift from the code.

use std::ffi::OsString;
use std::path::PathBuf;

use anyhow::Result;
use b10x_sandbox::docker::{self, DEFAULT_IMAGE, Identity};
use b10x_sandbox::{Confinement, Layout, Mapping, Options};

use crate::{SOURCE, front_matter};

/// Where the page lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/argv.md";

/// The host directory the examples work in. Not a real path: the layouts are built directly, as
/// [`Layout::plan`] would compute them, so generation does not depend on the machine.
const HOST: &str = "/srv/work";
/// The uid and gid the Docker examples show.
const IDENTITY: Identity = Identity {
    uid: 1000,
    gid: 1000,
};

/// `b10x-sandbox` in `/srv/work/app` with no `--dir`.
fn default_layout() -> Layout {
    Layout {
        ancestor: PathBuf::from(format!("{HOST}/app")),
        cwd: PathBuf::from("/workspace"),
        mappings: vec![Mapping {
            host: format!("{HOST}/app").into(),
            mount: "/workspace".into(),
        }],
    }
}

/// `b10x-sandbox --dir ../lib` in `/srv/work/app`.
fn mirrored_layout() -> Layout {
    Layout {
        ancestor: PathBuf::from(HOST),
        cwd: PathBuf::from("/workspace/app"),
        mappings: vec![
            Mapping {
                host: format!("{HOST}/app").into(),
                mount: "/workspace/app".into(),
            },
            Mapping {
                host: format!("{HOST}/lib").into(),
                mount: "/workspace/lib".into(),
            },
        ],
    }
}

fn lines(program: &str, argv: &[OsString]) -> String {
    let mut out = format!("{program}\n");
    for argument in argv {
        out.push_str(&argument.to_string_lossy());
        out.push('\n');
    }
    out
}

fn bubblewrap(layout: Layout) -> Result<String> {
    let confinement = Confinement::new(layout, Options::default(), ["/bin/sh"])?;
    Ok(lines("bwrap", &confinement.argv()?))
}

fn docker(layout: &Layout) -> String {
    let argv = docker::argv(
        layout,
        &Options::default(),
        DEFAULT_IMAGE,
        false,
        IDENTITY,
        &[OsString::from("/bin/sh")],
    );
    lines("docker", &argv)
}

/// The argument-list reference page.
pub fn page() -> Result<String> {
    let mut out = front_matter(
        "Argument lists",
        "Argument lists",
        "The exact bwrap and docker run argument lists b10x-sandbox builds, computed by the library.",
        2,
    );
    out.push_str(&format!(
        "# Argument lists\n\nGenerated by `sandbox-docs`, which calls the library \
         ([`src/confinement.rs`]({SOURCE}/src/confinement.rs), \
         [`src/docker.rs`]({SOURCE}/src/docker.rs)) for two layouts in a host directory \
         `{HOST}`: the default run in `{HOST}/app`, and `--dir ../lib` from there. The command is \
         `/bin/sh`, with no `TERM`, no `--ro` and no `--net`. Each block is what `b10x-sandbox \
         --dry-run` prints: the program, then one argument per line. Under Docker the uid and gid \
         are the caller's; the examples show {uid}:{gid}.\n\n\
         `--net` removes `--unshare-net` (bubblewrap) or `--network none` (Docker) and nothing \
         else. Each `--ro <PATH>` adds `--ro-bind <PATH> <PATH>` before the workspace, or \
         `-v <PATH>:<PATH>:ro` before the writable volumes. `TERM` from the caller adds one \
         `--setenv TERM` or `-e TERM=`.\n\n\
         ## Bubblewrap, default layout\n\nThe working directory is bound at `/workspace` itself, so \
         `/workspace` is not remounted read-only.\n\n```text\n{}```\n\n\
         ## Bubblewrap, mirrored layout\n\n`{HOST}` becomes `/workspace`, a tmpfs holding one \
         writable bind per directory, then remounted read-only so the parent itself takes no \
         writes.\n\n```text\n{}```\n\n\
         ## Docker, default layout\n\nNo tmpfs at `/workspace`: Docker refuses two mounts at one \
         destination.\n\n```text\n{}```\n\n\
         ## Docker, mirrored layout\n\n```text\n{}```\n",
        bubblewrap(default_layout())?,
        bubblewrap(mirrored_layout())?,
        docker(&default_layout()),
        docker(&mirrored_layout()),
        uid = IDENTITY.uid,
        gid = IDENTITY.gid,
    ));
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_examples_are_what_the_library_builds() {
        let page = page().unwrap();
        assert!(page.contains("# generated by sandbox-docs, do not edit"));
        let default = page.find("## Bubblewrap, default layout").unwrap();
        let mirrored = page.find("## Bubblewrap, mirrored layout").unwrap();
        assert!(!page[default..mirrored].contains("--remount-ro"));
        assert!(page[mirrored..].contains("--remount-ro\n/workspace\n"));
        assert!(page.contains("--bind\n/srv/work/lib\n/workspace/lib\n"));
        assert!(page.contains("--user\n1000:1000\n"));
        assert!(page.contains("-v\n/srv/work/lib:/workspace/lib\n"));
        assert!(page.contains("type=tmpfs,destination=/workspace,tmpfs-mode=0555"));
    }
}
