//! The CLI reference page, walked from the clap definition of `b10x-sandbox`
//! (`b10x_sandbox::cli::Cli`).

use clap::CommandFactory as _;

use crate::{SOURCE, cell, front_matter};

/// Where the CLI reference lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/cli.md";

fn text(value: Option<&clap::builder::StyledStr>) -> String {
    value.map(ToString::to_string).unwrap_or_default()
}

/// One row per argument of `command`: how it is written, whether it repeats, its default and its
/// help.
fn arguments(command: &clap::Command) -> Vec<[String; 4]> {
    command
        .get_arguments()
        .filter(|arg| !matches!(arg.get_id().as_str(), "help" | "version"))
        .map(|arg| {
            let value = arg
                .get_value_names()
                .and_then(|names| names.first().map(ToString::to_string));
            let takes_value = arg.get_num_args().is_some_and(|n| n.takes_values());
            let written = match (arg.get_long(), value, takes_value) {
                (Some(long), Some(value), true) => format!("--{long} <{value}>"),
                (Some(long), _, _) => format!("--{long}"),
                (None, Some(value), _) => format!("[{value}]..."),
                (None, None, _) => arg.get_id().as_str().to_uppercase(),
            };
            let repeats =
                arg.get_long().is_some() && matches!(arg.get_action(), clap::ArgAction::Append);
            let defaults: Vec<String> = arg
                .get_default_values()
                .iter()
                .map(|default| default.to_string_lossy().into_owned())
                .filter(|default| default != "false")
                .collect();
            let possible: Vec<String> = arg
                .get_possible_values()
                .iter()
                .filter(|_| arg.get_long().is_some() && takes_value)
                .map(|value| format!("`{}`", value.get_name()))
                .collect();
            let mut help = cell(&text(arg.get_long_help().or(arg.get_help())));
            if !help.is_empty() && !help.ends_with('.') {
                help.push('.');
            }
            if !possible.is_empty() {
                help.push_str(&format!(" One of {}.", possible.join(", ")));
            }
            [
                format!("`{written}`"),
                if repeats { "yes" } else { "no" }.to_owned(),
                if defaults.is_empty() {
                    "none".to_owned()
                } else {
                    format!("`{}`", defaults.join(", "))
                },
                help,
            ]
        })
        .collect()
}

/// The CLI reference page for the command line `root`.
pub fn page_for(mut root: clap::Command) -> String {
    root.build();
    let name = root.get_name().to_owned();
    let mut out = front_matter(
        &format!("{name} CLI reference"),
        &format!("{name} CLI"),
        &format!("Every option of the {name} command line, generated from its clap definition."),
        1,
    );
    out.push_str(&format!(
        "# `{name}`\n\nGenerated by `sandbox-docs` from the clap definition in \
         [`src/cli.rs`]({SOURCE}/src/cli.rs). `{name} --version` prints the version and \
         `{name} --help` prints the same text.\n\n> {}\n\n```text\n{}\n```\n\n\
         ## Options\n\n| Option | Repeatable | Default | Meaning |\n|---|---|---|---|\n",
        cell(&text(root.get_long_about().or(root.get_about()))),
        root.render_usage().to_string().trim_end(),
    ));
    for row in arguments(&root) {
        out.push_str(&format!("| {} |\n", row.join(" | ")));
    }
    out.push_str(
        "\n## Exit status\n\nUnder `--dry-run`, 0 after printing the argument list. Otherwise the \
         process is replaced by the backend's program, so the exit status is the sandboxed \
         command's (as `bwrap` or `docker run` report it). A refusal before that point — an input \
         path the layout refuses, a missing backend program, `dev.tty.legacy_tiocsti` set to 1 — \
         prints `b10x-sandbox: <reason>` on stderr and exits 2. Clap's own usage errors also exit \
         2.\n",
    );
    out
}

/// The CLI reference page for `b10x-sandbox`.
pub fn page() -> String {
    page_for(b10x_sandbox::cli::Cli::command())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_option_and_its_default_is_listed() {
        let page = page();
        assert!(page.contains("# generated by sandbox-docs, do not edit"));
        assert!(page.contains("custom_edit_url: null"));
        assert!(page.contains("Usage: b10x-sandbox [OPTIONS] [CMD]..."));
        assert!(page.contains("| `--dir <PATH>` | yes | none |"));
        assert!(page.contains("| `--ro <PATH>` | yes | none |"));
        assert!(page.contains("| `--net` | no | none | Keep the host network namespace. |"));
        assert!(page.contains("| `--backend <BACKEND>` | no | `bubblewrap` |"));
        assert!(page.contains("One of `bubblewrap`, `docker`."));
        assert!(page.contains("| `--image <NAME>` | no | `debian:stable-slim` |"));
        assert!(page.contains("| `[CMD]...` | no | none |"));
    }
}
