//! The crate list, from `cargo metadata --no-deps`: every workspace package, its directory, the
//! name Rust code uses for it, and its `description`.

use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, bail, ensure};
use serde_json::Value;

use crate::{TREE, cell, front_matter};

/// Where the crate list lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/crates.md";

/// One workspace package as the page lists it.
#[derive(Debug, PartialEq, Eq)]
struct Package {
    name: String,
    directory: String,
    /// The library name (`use <lib>`), when the package has a library.
    lib: Option<String>,
    /// The binaries it builds.
    bins: Vec<String>,
    description: String,
}

/// The packages of a `cargo metadata --format-version 1` document, sorted by name, with their
/// directories relative to `workspace_root`. A package without a description is refused: the page
/// would have nothing to say about it.
fn packages(metadata: &Value) -> Result<Vec<Package>> {
    let root = metadata["workspace_root"]
        .as_str()
        .context("cargo metadata names no workspace_root")?;
    let mut found = Vec::new();
    for package in metadata["packages"]
        .as_array()
        .context("cargo metadata lists no packages")?
    {
        let name = package["name"]
            .as_str()
            .context("a package has no name")?
            .to_owned();
        let manifest = package["manifest_path"]
            .as_str()
            .with_context(|| format!("{name} has no manifest_path"))?;
        let directory = Path::new(manifest)
            .parent()
            .and_then(|dir| dir.strip_prefix(root).ok())
            .with_context(|| format!("{name} lies outside the workspace"))?
            .to_string_lossy()
            .into_owned();
        let Some(description) = package["description"].as_str() else {
            bail!("{name} has no description in its Cargo.toml");
        };
        let mut lib = None;
        let mut bins = Vec::new();
        for target in package["targets"].as_array().into_iter().flatten() {
            let kinds: Vec<&str> = target["kind"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect();
            let target_name = target["name"].as_str().unwrap_or_default().to_owned();
            if kinds.contains(&"lib") {
                lib = Some(target_name);
            } else if kinds.contains(&"bin") {
                bins.push(target_name);
            }
        }
        bins.sort();
        found.push(Package {
            name,
            directory,
            lib,
            bins,
            description: description.trim().to_owned(),
        });
    }
    ensure!(!found.is_empty(), "cargo metadata lists no packages");
    found.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(found)
}

fn table(packages: &[&Package]) -> String {
    let mut out =
        String::from("| Package | Directory | In Rust | What it is |\n|---|---|---|---|\n");
    for package in packages {
        let mut uses = Vec::new();
        if let Some(lib) = &package.lib {
            uses.push(format!("`use {lib}`"));
        }
        for bin in &package.bins {
            uses.push(format!("binary `{bin}`"));
        }
        let (shown, link) = if package.directory.is_empty() {
            (".".to_owned(), TREE.to_owned())
        } else {
            (
                package.directory.clone(),
                format!("{TREE}/{}", package.directory),
            )
        };
        out.push_str(&format!(
            "| `{}` | [`{shown}`]({link}) | {} | {} |\n",
            package.name,
            uses.join(", "),
            cell(&package.description),
        ));
    }
    out
}

/// The crate list page for the packages of `metadata`.
fn page_for(metadata: &Value) -> Result<String> {
    let all = packages(metadata)?;
    let (components, tooling): (Vec<&Package>, Vec<&Package>) = all
        .iter()
        .partition(|package| package.name.starts_with("b10x-"));
    let mut out = front_matter(
        "Crates",
        "Crates",
        "Every package of the Sandbox workspace, generated from cargo metadata.",
        3,
    );
    out.push_str(&format!(
        "# Crates\n\nGenerated by `sandbox-docs` from `cargo metadata --no-deps`: every package of \
         the workspace, with the `description` its `Cargo.toml` gives. There are {} packages. None \
         is on a registry; depend on them by Git or by path.\n\n## Components\n\nThe package an \
         application or an operator uses: the `b10x_sandbox` library and the `b10x-sandbox` \
         binary built from it.\n\n{}\n## Repository tooling\n\nGenerators and checks the \
         repository's own gate runs. Nothing outside the repository depends on them.\n\n{}",
        all.len(),
        table(&components),
        table(&tooling),
    ));
    Ok(out)
}

/// The crate list page for the workspace at `root`, read with `cargo metadata`.
pub fn page(root: &Path) -> Result<String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(&cargo)
        .args([
            "metadata",
            "--no-deps",
            "--format-version",
            "1",
            "--manifest-path",
        ])
        .arg(root.join("Cargo.toml"))
        .output()
        .context("running cargo metadata")?;
    if !output.status.success() {
        bail!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let metadata: Value =
        serde_json::from_slice(&output.stdout).context("parsing cargo metadata")?;
    page_for(&metadata)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn metadata(description: Option<&str>) -> Value {
        serde_json::json!({
            "workspace_root": "/w",
            "packages": [
                {
                    "name": "sandbox-docs",
                    "manifest_path": "/w/crates/sandbox-docs/Cargo.toml",
                    "description": "Generates pages.",
                    "targets": [{"kind": ["bin"], "name": "sandbox-docs"}]
                },
                {
                    "name": "b10x-sandbox",
                    "manifest_path": "/w/Cargo.toml",
                    "description": description,
                    "targets": [
                        {"kind": ["lib"], "name": "b10x_sandbox"},
                        {"kind": ["bin"], "name": "b10x-sandbox"},
                        {"kind": ["test"], "name": "cli"}
                    ]
                }
            ]
        })
    }

    #[test]
    fn packages_are_sorted_split_and_linked() {
        let page = page_for(&metadata(Some("The sandbox | tool."))).unwrap();
        assert!(page.contains("# generated by sandbox-docs, do not edit"));
        assert!(page.contains("There are 2 packages."));
        let components = page.find("## Components").unwrap();
        let tooling = page.find("## Repository tooling").unwrap();
        let tool = page.find("| `b10x-sandbox` |").unwrap();
        let docs = page.find("| `sandbox-docs` |").unwrap();
        assert!(components < tool && tool < tooling && tooling < docs);
        assert!(page.contains(
            "| `b10x-sandbox` | [`.`](https://github.com/beyond10x/sandbox/tree/main) | `use b10x_sandbox`, binary `b10x-sandbox` | The sandbox \\| tool. |"
        ));
        assert!(page.contains(
            "[`crates/sandbox-docs`](https://github.com/beyond10x/sandbox/tree/main/crates/sandbox-docs)"
        ));
    }

    #[test]
    fn a_package_without_a_description_is_refused() {
        let error = page_for(&metadata(None)).unwrap_err().to_string();
        assert!(error.contains("b10x-sandbox has no description"), "{error}");
    }
}
