#![forbid(unsafe_code)]
// The pages are built by appending formatted Markdown to one String; `write!` would only add an
// infallible Result to every line.
#![allow(clippy::format_push_string)]
//! Generates the derivable part of the Sandbox documentation site, checks it for drift, and binds
//! a built site to its source commit. The site build itself is Docusaurus.
//!
//! It generates four files:
//!
//! - the CLI reference (`reference/cli.md`), walked from [`b10x_sandbox::cli::Cli`];
//! - the argument lists (`reference/argv.md`), computed by the library for fixed example layouts;
//! - the crate list (`reference/crates.md`), from `cargo metadata --no-deps`;
//! - the status data (`website/data/status.json`), from [`status::CAPABILITIES`], where every
//!   shipped item names the test that holds it and generation fails when that test is gone.
mod argv;
mod cli;
mod crates;
mod status;

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail, ensure};
use clap::{Parser, Subcommand};

/// The first line of every generated page's front matter.
const FRONT_MATTER_HEADER: &str = "# generated by sandbox-docs, do not edit";
/// The line every generated Markdown page carries directly after its front matter.
const HEADER: &str = "<!-- generated by sandbox-docs, do not edit -->";
/// A file in the repository on GitHub, by path.
const SOURCE: &str = "https://github.com/beyond10x/sandbox/blob/main";
/// A directory in the repository on GitHub, by path.
const TREE: &str = "https://github.com/beyond10x/sandbox/tree/main";
/// Every documentation page, generated or written by hand, relative to the repository root.
const DOCS: &str = "website/docs";

/// Whether `line` matches `^:::[a-z]+ +\S`: an admonition whose title is not in brackets, which
/// Docusaurus prints as raw text.
fn is_raw_admonition(line: &str) -> bool {
    let Some(rest) = line.strip_prefix(":::") else {
        return false;
    };
    let kind = rest.bytes().take_while(u8::is_ascii_lowercase).count();
    let rest = &rest[kind..];
    let spaces = rest.bytes().take_while(|b| *b == b' ').count();
    kind > 0
        && spaces > 0
        && rest[spaces..]
            .chars()
            .next()
            .is_some_and(|c| !c.is_whitespace())
}

/// `file:line` of every raw admonition title in the Markdown and MDX pages under `dir`.
fn raw_admonitions(dir: &Path) -> Result<Vec<String>> {
    let mut found = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
        .collect::<Result<_, _>>()?;
    entries.sort_by_key(fs::DirEntry::path);
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            found.extend(raw_admonitions(&path)?);
        } else if path
            .extension()
            .is_some_and(|ext| ext == "md" || ext == "mdx")
        {
            for (n, line) in fs::read_to_string(&path)?.lines().enumerate() {
                if is_raw_admonition(line) {
                    found.push(format!("{}:{}", path.display(), n + 1));
                }
            }
        }
    }
    Ok(found)
}

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the Sandbox documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate the reference pages and the status data, or check them for drift.
    Generate {
        /// Write nothing; fail when a generated file is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// The project-site publication record for one build of the `/sandbox/` site.
fn site_manifest(commit: &str) -> Result<String> {
    ensure!(
        commit.len() == 40
            && commit.bytes().all(|b| b.is_ascii_hexdigit())
            && commit != "0".repeat(40),
        "commit must be a nonzero full Git revision"
    );
    Ok(format!(
        "{{\n  \"baseUrl\": \"/sandbox/\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"sandbox\",\n  \"schema\": \"b10x-project-site/v1\"\n}}"
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    ensure!(
        site.join("index.html").is_file(),
        "{} holds no built site",
        site.display()
    );
    fs::create_dir_all(site.join(".well-known"))?;
    fs::write(site.join(".well-known/b10x-site.json"), manifest)
        .context("writing site provenance")?;
    fs::write(site.join(".nojekyll"), "")?;
    Ok(())
}

fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

/// `value` as one Markdown table cell: on one line, with `|` escaped.
fn cell(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// The front matter of a generated page: the generator line, title, label, sidebar position,
/// description and no edit link, then the generated-page comment.
fn front_matter(title: &str, label: &str, description: &str, position: u32) -> String {
    format!(
        "---\n{FRONT_MATTER_HEADER}\ntitle: {}\nsidebar_label: {}\nsidebar_position: {position}\ndescription: {}\ncustom_edit_url: null\n---\n\n{HEADER}\n\n",
        yaml_string(title),
        yaml_string(label),
        yaml_string(description),
    )
}

/// Every generated file, keyed by path relative to the repository root.
fn outputs(root: &Path) -> Result<Vec<(&'static str, String)>> {
    Ok(vec![
        (cli::PAGE, cli::page()),
        (argv::PAGE, argv::page()?),
        (crates::PAGE, crates::page(root)?),
        (status::DATA, status::document(root)?),
    ])
}

fn main() -> Result<()> {
    match Cli::parse().command {
        Action::Generate { check, root } => {
            for (relative, content) in outputs(&root)? {
                let path = root.join(relative);
                if check {
                    match fs::read_to_string(&path) {
                        Ok(found) if found == content => println!("{relative}: current"),
                        Ok(_) => bail!("{relative} is stale or edited; run `task docs-generate`"),
                        Err(_) => bail!("{relative} is missing; run `task docs-generate`"),
                    }
                } else {
                    if let Some(parent) = path.parent() {
                        fs::create_dir_all(parent)?;
                    }
                    fs::write(&path, content)?;
                    println!("{relative}: written");
                }
            }
            if check {
                let raw = raw_admonitions(&root.join(DOCS))?;
                if !raw.is_empty() {
                    bail!(
                        "raw admonition titles (write `:::kind[Title]`): {}",
                        raw.join(", ")
                    );
                }
                println!("{DOCS}: no raw admonition titles");
            }
        }
        Action::Provenance { site, commit } => {
            write_provenance(&site, &commit)?;
            println!("{}: bound to {commit}", site.display());
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("sandbox-docs-test-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn provenance_names_the_commit_and_refuses_a_bad_one() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let manifest = site_manifest(commit).unwrap();
        assert!(manifest.contains(&format!("\"commit\": \"{commit}\"")));
        assert!(manifest.contains("\"schema\": \"b10x-project-site/v1\""));
        assert!(manifest.contains("\"baseUrl\": \"/sandbox/\""));
        assert!(site_manifest("e86f43d").is_err());
        assert!(site_manifest(&"0".repeat(40)).is_err());
        assert!(site_manifest(&format!("{}\"", &commit[..39])).is_err());

        let site = scratch("provenance");
        assert!(write_provenance(&site, commit).is_err());
        fs::write(site.join("index.html"), "").unwrap();
        write_provenance(&site, commit).unwrap();
        let written = fs::read_to_string(site.join(".well-known/b10x-site.json")).unwrap();
        assert_eq!(written, manifest);
        fs::remove_dir_all(site).unwrap();
    }

    #[test]
    fn raw_admonition_titles_are_found_and_bracketed_ones_pass() {
        for raw in [":::caution Planned", ":::note  These", ":::info Decided"] {
            assert!(is_raw_admonition(raw), "{raw}");
        }
        for fine in [
            ":::caution[Planned]",
            ":::",
            ":::note",
            ":::note ",
            "::: note T",
        ] {
            assert!(!is_raw_admonition(fine), "{fine}");
        }
        let dir = scratch("admonitions");
        fs::create_dir_all(dir.join("concepts")).unwrap();
        fs::write(dir.join("index.md"), ":::caution[Planned]\nok\n:::\n").unwrap();
        fs::write(dir.join("concepts/a.md"), "text\n:::caution Planned\n:::\n").unwrap();
        let found = raw_admonitions(&dir).unwrap();
        assert_eq!(found.len(), 1);
        assert!(found[0].ends_with("concepts/a.md:2"), "{found:?}");
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn every_generated_file_is_current_in_this_tree() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        for (relative, content) in outputs(&root).unwrap() {
            let found = fs::read_to_string(root.join(relative))
                .unwrap_or_else(|_| panic!("{relative} is missing; run `task docs-generate`"));
            assert!(
                found == content,
                "{relative} is stale; run `task docs-generate`"
            );
        }
    }
}
