import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// Pages under docs/reference/ and data/status.json are generated by `sandbox-docs generate`;
// everything else is written by hand.
const config: Config = {
  title: 'Sandbox',
  tagline: 'Respawn a shell or one command in a bubblewrap sandbox that sees only the directories you name.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  url: 'https://beyond10x.github.io',
  baseUrl: '/sandbox/',

  organizationName: 'beyond10x',
  projectName: 'sandbox',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/sandbox/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'Sandbox',
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/getting-started', label: 'Get started', position: 'left'},
        {to: '/docs/reference/cli', label: 'CLI', position: 'left'},
        {to: '/docs/status', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/sandbox', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/docs/'},
            {label: 'Getting started', to: '/docs/getting-started'},
            {label: 'Run tests in the sandbox', to: '/docs/guides/run-tests-in-the-sandbox'},
            {label: 'Use the Docker backend', to: '/docs/guides/use-the-docker-backend'},
            {label: 'Embed the library', to: '/docs/guides/embed-the-library'},
            {label: 'What is confined', to: '/docs/concepts/confinement'},
            {label: 'The workspace layout', to: '/docs/concepts/workspace-layout'},
            {label: 'b10x-sandbox CLI', to: '/docs/reference/cli'},
            {label: 'Argument lists', to: '/docs/reference/argv'},
            {label: 'Status', to: '/docs/status'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Source', href: 'https://github.com/beyond10x/sandbox'},
            {label: 'Changelog', href: 'https://github.com/beyond10x/sandbox/blob/main/CHANGELOG.md'},
          ],
        },
      ],
      copyright: 'A beyond10x project. Sandbox · Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json', mark: 'Sb'});
